version: 2
jobs:
  build:
    working_directory: ~/spring-back/recipe
    docker:
      # specify the version you desire here
      - image: maven:1.8.0-jdk-8

      environment:
        DATABASE_URL: jdbc:mysql://127.0.0.1:8080/LensFlats
        DATABASE_USER: root
        DATABASE_PASSWORD: root
          - image: mysql:5.7

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/spring-back

      # Download and cache dependencies
      - restore_cache:
          keys:
            - recipe-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - recipe-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: recipe-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test
