
version: 2
jobs:
  build:
    docker:
      - image: maven:3.5.0-jdk-8
        environment:
          DATABASE_URL: jdbc:mysql://192.168.1.3:8080/lensflats
          DATABASE_USER: root
          DATABASE_PASSWORD: root
      - image: mysql:5.7

    working_directory: ~/repo

    steps:
      - checkout
      - run: apt-get update -qq && apt-get install -y mysql
      - run:
          command: |
            mysql -h 127.0.0.1 -U mysql -c "CREATE DATABASE lensflats;"
            mysql -h 127.0.0.1 -U mysql -c "CREATE USER root WITH PASSWORD 'root'; GRANT ALL PRIVILEGES ON DATABASE lensflats TO root;"
      - run: mvn test
